### ISSUE TITLE
LocalTuya not loaded

### ISSUE THREAD

**Issue by Slonik** [rospogrigio/localtuya-homeassistant#2063]
## The problem
LocalTuya not loaded

## Environment

- Localtuya version:  Version 5.2.1
- Home Assistant Core version:  
Installation method Home Assistant OS
Core 2025.8.3
Supervisor 2025.08.1
Operating System 16.1
Frontend 20250811.1
- [] Does the device work using the Home Assistant Tuya Cloud component ? 
- [] Does the device work using the Tinytuya (https://github.com/jasonacox/tinytuya) command line tool ? 
- [] Was the device working with earlier versions of localtuya ? Which one? 
- [] Are you using the Tuya/SmartLife App in parallel ? 

## Steps to reproduce

1. Add LocalTuya to HA & enter Tuya secrects and more.

## Provide Home Assistant traceback/logs

```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:350
First occurred: 14:05:44 (1 occurrence)
Last logged: 14:05:44

Detected that custom integration 'localtuya' sets option flow config_entry explicitly, which is deprecated at custom_components/localtuya/config_flow.py, line 396: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/rospogrigio/localtuya/issues```

**Comment by edgicat** [comment]
Same problem almost 1 month after updating to HA 2025.8.0 have rolled back to 2025.7.0.

Need resolution

**Comment by scarelli** [comment]
Same issue here

**Comment by m-s-e** [comment]
Same issue for me after updating to 2025.8.3
The bug report does say "This will stop working in Home Assistant 2025.12", so there's a couple of months yet!

**Comment by SkipzNL** [comment]
I have the same, since a week or so. Only I have four errormessages:

```
Logger: homeassistant.helpers.frame
Bron: helpers/frame.py:335
Eerst voorgekomen: 19:22:49 (1 gebeurtenis)
Laatst gelogd: 19:22:49

Detected that custom integration 'localtuya' sets option flow config_entry explicitly, which is deprecated at custom_components/localtuya/config_flow.py, line 396: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/rospogrigio/localtuya/issues
```

```
Logger: homeassistant.setup
Bron: setup.py:426
Eerst voorgekomen: 29 augustus 2025 om 14:45:27 (1 gebeurtenis)
Laatst gelogd: 29 augustus 2025 om 14:45:27

Error during setup of component localtuya: 'HomeAssistant' object has no attribute 'helpers'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 426, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/localtuya/__init__.py", line 165, in async_setup
    hass.helpers.service.async_register_admin_service(
    ^^^^^^^^^^^^
AttributeError: 'HomeAssistant' object has no attribute 'helpers'
```

```
Logger: homeassistant.components.vacuum
Bron: helpers/deprecation.py:222
integratie: Stofzuiger ([documentatie](https://www.home-assistant.io/integrations/vacuum), [problemen](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+vacuum%22))
Eerst voorgekomen: 29 augustus 2025 om 14:45:26 (12 gebeurtenissen)
Laatst gelogd: 29 augustus 2025 om 14:45:27

STATE_DOCKED was used from localtuya, this is a deprecated constant which will be removed in HA Core 2026.1. Use VacuumActivity.DOCKED instead, please report it to the author of the 'localtuya' custom integration
STATE_ERROR was used from localtuya, this is a deprecated constant which will be removed in HA Core 2026.1. Use VacuumActivity.ERROR instead, please report it to the author of the 'localtuya' custom integration
STATE_IDLE was used from localtuya, this is a deprecated constant which will be removed in HA Core 2026.1. Use VacuumActivity.IDLE instead, please report it to the author of the 'localtuya' custom integration
STATE_PAUSED was used from localtuya, this is a deprecated constant which will be removed in HA Core 2026.1. Use VacuumActivity.PAUSED instead, please report it to the author of the 'localtuya' custom integration
STATE_RETURNING was used from localtuya, this is a deprecated constant which will be removed in HA Core 2026.1. Use VacuumActivity.RETURNING instead, please report it to the author of the 'localtuya' custom integration
```

```
Logger: homeassistant.components.light
Bron: helpers/deprecation.py:222
integratie: Licht ([documentatie](https://www.home-assistant.io/integrations/light), [problemen](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+light%22))
Eerst voorgekomen: 29 augustus 2025 om 14:45:26 (10 gebeurtenissen)
Laatst gelogd: 29 augustus 2025 om 14:45:26

ATTR_COLOR_TEMP was used from localtuya, this is a deprecated constant which will be removed in HA Core 2026.1. Use kelvin equivalent (ATTR_COLOR_TEMP_KELVIN) instead, please report it to the author of the 'localtuya' custom integration
SUPPORT_BRIGHTNESS was used from localtuya, this is a deprecated constant which will be removed in HA Core 2026.1. Use supported_color_modes instead, please report it to the author of the 'localtuya' custom integration
SUPPORT_COLOR was used from localtuya, this is a deprecated constant which will be removed in HA Core 2026.1. Use supported_color_modes instead, please report it to the author of the 'localtuya' custom integration
SUPPORT_COLOR_TEMP was used from localtuya, this is a deprecated constant which will be removed in HA Core 2026.1. Use supported_color_modes instead, please report it to the author of the 'localtuya' custom integration
SUPPORT_EFFECT was used from localtuya, this is a deprecated constant which will be removed in HA Core 2026.1. Use LightEntityFeature.EFFECT instead, please report it to the author of the 'localtuya' custom integration
```
