### ISSUE TITLE
Vacuum entity fails to load on Home Assistant Core 2026.9+: `AttributeError: type object 'VacuumEntityFeature' has no attribute 'BATTERY'`

### ISSUE THREAD

**Issue by marcoschicote** [rospogrigio/localtuya-homeassistant#2285]
## The problem

Note up front: this isn't a "localtuya update broke it" case — the axis that
changed is **Home Assistant Core**, not localtuya. Same localtuya version
(5.2.3) works fine on Core 2026.8.3 and fails immediately on Core 2026.9.1.

Home Assistant Core removed `VacuumEntityFeature.BATTERY` entirely in the
`2026.9.x` line (it existed as `BATTERY = 64` in `2026.8.3`'s
`homeassistant/components/vacuum/const.py`, gone by `2026.9.1`). `vacuum.py`
unconditionally references it whenever a device has `CONF_BATTERY_DP`
configured:

```python
if self.has_config(CONF_BATTERY_DP):
    supported_features = supported_features | VacuumEntityFeature.BATTERY
```

Since `supported_features` is read during entity setup (via
`capability_attributes` in HA Core's `vacuum/__init__.py`), this raises an
`AttributeError` that aborts the *entire* entity — not just battery
reporting. Any vacuum configured with a battery data point simply
disappears from Home Assistant after updating to `2026.9.x`.

Confirmed this isn't already fixed: the same unconditional reference is
present not just in the installed `5.2.3`, but also in the latest release
(`v5.2.5`) and the current `master` branch.

## Environment

- Localtuya version: 5.2.3 (via HACS)
- Home Assistant Core version: 2026.9.1 (also reproduces on any `2026.9.x`, since the removed enum member is the cause, not something version-specific within 2026.9)
- [ ] Does the device work using the Home Assistant Tuya Cloud component? — not tested
- [ ] Does the device work using the Tinytuya command line tool? — not tested
- [x] Was the device working with earlier versions of **Home Assistant Core**? Yes — same localtuya 5.2.3, works fine on Core 2026.8.3, fails on 2026.9.1. (Not a localtuya-version regression.)
- [ ] Are you using the Tuya/SmartLife App in parallel? — not applicable to this bug (fails at Python import/entity-setup time, before any device communication happens)

## Steps to reproduce

1. Configure a vacuum entity in localtuya with a Battery DP set (`CONF_BATTERY_DP`).
2. Run Home Assistant Core `2026.9.0` or later.
3. Vacuum entity fails to set up; error appears in logs.

## DP dump

Not applicable — this fails at Python attribute-resolution time during
entity setup, before any device communication or DP data is involved. Not
device-specific; will reproduce for any vacuum config with a Battery DP set.

## Provide Home Assistant traceback/logs

```
ERROR (MainThread) [homeassistant.components.vacuum] Error adding entity None for domain vacuum with platform localtuya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 725, in _async_add_entities
    await self._async_add_entity(
        entity, False, entity_registry, config_subentry_id
    )
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1041, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/vacuum/__init__.py", line 203, in capability_attributes
    if VacuumEntityFeature.FAN_SPEED in self.supported_features:
                                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/vacuum.py", line 123, in supported_features
    supported_features = supported_features | VacuumEntityFeature.BATTERY
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'VacuumEntityFeature' has no attribute 'BATTERY'
```

Also present in logs, a related but separate deprecation warning (not the
crash itself, doesn't stop the entity by itself — flagging since it's
likely the same underlying HA migration):

```
WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'localtuya' is setting the battery_level which has been deprecated. Integration localtuya should implement a sensor instead with a correct device class and link it to the same device. This will stop working in Home Assistant 2026.8, please create a bug report at https://github.com/rospogrigio/localtuya/issues
```

## Additional information

Confirmed the minimal fix — guard the reference so it degrades gracefully
on Core versions where the enum member no longer exists, while staying
compatible with older Core versions that still have it:

```python
if self.has_config(CONF_BATTERY_DP) and hasattr(VacuumEntityFeature, "BATTERY"):
    supported_features = supported_features | VacuumEntityFeature.BATTERY
```

Applied this locally and it resolves the crash. Happy to open a PR with
this fix (plus, if useful, tackling the `battery_level` deprecation warning
above by moving to a proper battery sensor entity per HA's guidance) if
that's preferred over a maintainer picking it up.

**Comment by marcoschicote** [comment]
Opened a fix: #2286 — guards the `VacuumEntityFeature.BATTERY` reference with `hasattr()` so it degrades gracefully on Core 2026.9+.

🤖 Generated with [Claude Code](https://claude.com/claude-code)
